"use client";

import { useState } from "react";
import { BriefcaseBusiness, ChevronDown, FileText, Filter, FolderOpen, LockKeyhole, MoreHorizontal, Plus, Search, Settings2, Sparkles, Target, TrendingUp, Upload, Users } from "lucide-react";
import { Badge, Button, Card, Progress } from "@/components/ui";

const stages = ["First filter", "Meet-up", "Task / senior review", "Final / team sync", "Offer"];
const applications = [
  { company: "Northstar Labs", role: "Product Designer, Identity", date: "Example", stage: 0, cv: "Example CV", portfolio: "Example portfolio", tone: "bg-sky-400" },
  { company: "Loomline", role: "Product Designer, Enterprise", date: "Example", stage: 1, cv: "Example CV", portfolio: "Example portfolio", tone: "bg-violet-400" },
  { company: "Willow Bank", role: "Staff Product Designer", date: "Example", stage: 2, cv: "Example CV", portfolio: "Example portfolio", tone: "bg-emerald-400" },
  { company: "Common Ground", role: "Lead Product Designer", date: "Example", stage: 3, cv: "Example CV", portfolio: "Example portfolio", tone: "bg-orange-400" },
];

export default function Home() {
  const [activeView, setActiveView] = useState("Overview");
  const [showAdd, setShowAdd] = useState(false);
  return (
    <main className="min-h-screen bg-background">
      <header className="border-b bg-card/70">
        <div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-4 lg:px-8">
          <div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-md bg-primary text-sm font-bold text-primary-foreground">JG</div><div><p className="font-semibold tracking-tight">Job Hunting Ground</p><p className="text-xs text-muted-foreground">Private workspace</p></div></div>
          <div className="flex items-center gap-2"><Badge className="border-emerald-400/30 bg-emerald-400/10 text-emerald-300"><LockKeyhole className="mr-1 h-3 w-3" /> Local only</Badge><Button variant="ghost" size="icon" aria-label="Settings"><Settings2 className="h-4 w-4" /></Button><div className="hidden h-8 w-8 items-center justify-center rounded-full bg-muted text-xs font-semibold sm:flex">RY</div></div>
        </div>
      </header>
      <div className="mx-auto grid max-w-[1440px] lg:grid-cols-[220px_1fr]">
        <aside className="hidden border-r px-4 py-6 lg:block"><p className="mb-3 px-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">Workspace</p>{["Overview", "Applications", "Versions", "Feedback", "Settings"].map((item) => <button key={item} onClick={() => setActiveView(item)} className={`mb-1 flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-left text-sm transition-colors ${activeView === item ? "bg-muted text-foreground" : "text-muted-foreground hover:bg-muted/60 hover:text-foreground"}`}><span className="h-1.5 w-1.5 rounded-full bg-primary/70" />{item}</button>)}<div className="mt-10 rounded-lg border bg-muted/40 p-4"><p className="mb-2 text-xs font-medium">Privacy mode</p><p className="text-xs leading-5 text-muted-foreground">Your records stay in this browser. Export a backup before changing devices.</p></div></aside>
        <section className="min-w-0 px-5 py-6 lg:px-8 lg:py-8">
          <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-primary">{activeView}</p><h1 className="text-3xl font-semibold tracking-tight">Keep the search moving.</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">A private record of the opportunities, versions and feedback that shape your next move.</p></div><Button onClick={() => setShowAdd(true)}><Plus className="h-4 w-4" /> Add application</Button></div>
          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={BriefcaseBusiness} label="Active applications" value="4" note="All in first filter" /><Stat icon={Target} label="Interviews" value="0" note="Keep the record current" /><Stat icon={TrendingUp} label="Response rate" value="--" note="Needs more history" /><Stat icon={FileText} label="Current CV" value="v2" note="Last updated today" /></div>
          <div className="mt-8 grid gap-6 xl:grid-cols-[1.4fr_0.6fr]">
            <Card className="overflow-hidden"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">Application pipeline</h2><p className="mt-1 text-xs text-muted-foreground">Five stages, one clear next action.</p></div><Button variant="outline" size="sm"><Filter className="h-3.5 w-3.5" /> Filter</Button></div><div className="grid grid-cols-5 border-b bg-muted/25 px-5 py-4">{stages.map((stage, index) => <div key={stage} className="min-w-0 pr-2"><div className="mb-2 flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${index === 0 ? "bg-primary" : "bg-muted-foreground/40"}`} /><span className="truncate text-[11px] font-medium text-muted-foreground">{stage}</span></div><p className="text-xl font-semibold">{index === 0 ? "4" : "0"}</p></div>)}</div><div className="divide-y">{applications.map((application) => <ApplicationRow key={application.company} {...application} />)}</div></Card>
            <div className="space-y-6"><Card className="p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold">Version library</h2><p className="mt-1 text-xs text-muted-foreground">What was sent, and when.</p></div><FolderOpen className="h-4 w-4 text-muted-foreground" /></div><Version label="Example CV v2" detail="Current working version" progress={85} /><Version label="Example CV v1" detail="Previous version" progress={60} /><Version label="Example portfolio" detail="Current deployed version" progress={100} /><Button variant="outline" className="mt-4 w-full"><Upload className="h-4 w-4" /> Add local version</Button></Card><Card className="panel-grid p-5"><Sparkles className="mb-4 h-5 w-5 text-primary" /><h2 className="font-semibold">Feedback loop</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Capture interview signals and turn them into precise improvements for the next application.</p><Button variant="outline" className="mt-5 w-full">Open feedback log</Button></Card></div>
          </div>
          <div className="mt-8 grid gap-6 md:grid-cols-2"><Card className="p-5"><div className="flex items-start gap-4"><div className="rounded-md bg-muted p-2.5"><Users className="h-5 w-5 text-primary" /></div><div><h2 className="font-semibold">Interview readiness</h2><p className="mt-1 text-sm text-muted-foreground">Prepare around the five stages without losing the evidence behind each application.</p></div></div><Progress value={20} className="mt-5" /><div className="mt-2 flex justify-between text-xs text-muted-foreground"><span>Example data only</span><span>20%</span></div></Card><Card className="p-5"><div className="flex items-start justify-between"><div><h2 className="font-semibold">Next action</h2><p className="mt-1 text-sm text-muted-foreground">Follow up when a status changes.</p></div><MoreHorizontal className="h-4 w-4 text-muted-foreground" /></div><div className="mt-5 flex items-center gap-3 rounded-md border bg-muted/30 p-3"><div className="h-2 w-2 rounded-full bg-primary" /><div><p className="text-sm font-medium">Review first-filter preparation</p><p className="mt-1 text-xs text-muted-foreground">Example application</p></div><ChevronDown className="ml-auto h-4 w-4 text-muted-foreground" /></div></Card></div>
        </section>
      </div>
      {showAdd && <div className="fixed inset-0 z-20 flex items-center justify-center bg-black/60 p-5"><Card className="w-full max-w-md p-6"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-lg font-semibold">Add application</h2><p className="mt-1 text-sm text-muted-foreground">The form will save locally in the next iteration.</p></div><Button variant="ghost" size="icon" onClick={() => setShowAdd(false)} aria-label="Close">×</Button></div><div className="space-y-3"><input className="h-10 w-full rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring" placeholder="Company" /><input className="h-10 w-full rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring" placeholder="Role" /><Button className="w-full" onClick={() => setShowAdd(false)}>Save locally</Button></div></Card></div>}
    </main>
  );
}

function Stat({ icon: Icon, label, value, note }: { icon: typeof BriefcaseBusiness; label: string; value: string; note: string }) { return <Card className="p-5"><div className="mb-5 flex items-center justify-between"><span className="text-sm text-muted-foreground">{label}</span><Icon className="h-4 w-4 text-primary" /></div><p className="text-3xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></Card>; }
function Version({ label, detail, progress }: { label: string; detail: string; progress: number }) { return <div className="mb-4"><div className="mb-2 flex justify-between gap-3"><div><p className="text-sm font-medium">{label}</p><p className="text-xs text-muted-foreground">{detail}</p></div><span className="text-xs text-muted-foreground">{progress}%</span></div><Progress value={progress} /></div>; }
function ApplicationRow({ company, role, date, cv, portfolio, tone }: (typeof applications)[number]) { return <div className="flex flex-col gap-4 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-md ${tone} text-xs font-bold text-slate-950`}>{company.slice(0, 2).toUpperCase()}</div><div className="min-w-0"><p className="truncate text-sm font-medium">{company}</p><p className="truncate text-xs text-muted-foreground">{role}</p></div></div><div className="flex items-center gap-4 pl-12 text-xs text-muted-foreground sm:pl-0"><span>{date}</span><Badge className="border-primary/30 bg-primary/10 text-primary">First filter</Badge><span className="hidden md:inline">{cv} · {portfolio}</span><Button variant="ghost" size="icon" aria-label={`Open ${company}`}><Search className="h-4 w-4" /></Button></div></div>; }
